name: Android

on:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: KtLint
        run: ./gradlew ktlintCheck
      - name: Lint
        run: ./gradlew lintDebug
      - name: Tests and code coverage
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
